### PR TITLE
Made the ServiceProvider compatible with Laravel 5.4

### PR DESCRIPTION
**Pull request by pvgennip**
Thank you for the nice ServiceProvider!
I wanted to use it with the newest version of Laravel, but composer told me that your version was not compatible, so I made it compatible.

I had to change the composer.json to test is, but maybe you can review the changes and make your version also compatible with Laravel 5.4.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Looks good to me, except `composer.json` :)

Cc: @apictapx

**Comment by pvgennip** [comment]
No problem. You can exclude composer.json when merging. That was necessary to test :-)

**Comment by sergeyklay** [comment]
@pvgennip I'm going to merge this. But could you please update composer.json and the README.md first.

**Comment by pvgennip** [comment]
I will commit another PR with the right files

**Pull request closed without merging**
